# movies_list = [
#   'Golden Boys','Kaccha Limboo','Not A Love Story','Qaidi Band','Chaatwali','Shuttlecock Boys','Dirty Marriage',
#   'Future To Bright Hai Ji','Ghajini','Taare Zameen Par','Mangal Pandey - The Rising','Fanaa','Dangal','3 Idiots','PK',
#   'Rang De Basanti','Talaash','Dhoom 3','Pyaar Mein Aisa Hota Hai','Gurjar Aandolan - A Fight For Right','Yehi Hai High Society',
#   'Say Yes To Love','Dreams - Sapnay Sach Honge...','Three - Love Lies Betrayal','Malegaon Me Gadbad Ghotala',
#   'Khota Sikka - Jaat Ke Thaath','Hi Fi Log','Dev D','One By Two','Oye Lucky! Lucky Oye!','Socha Na Tha','Happy Bhaag Jayegi',
#   'Manorama Six Feet Under','Honeymoon Travels Pvt. Ltd.','Ek Chalis Ki Last Local','Ahista Ahista','Lottery'
# ]

movies_list=['golden boys','kaccha limboo','not a love story','qaidi band','chaatwali','shuttlecock boys','dirty marriage',
              'future to bright hai ji','ghajini','taare zameen par','mangal pandey the rising','fanaa','dangal','3 idiots',
              'pk','rang de basanti','talaash','dhoom 3','pyaar mein aisa hota hai','gurjar aandolan - a fight for right',
              'yehi hai high society','say yes to love','dreams - sapnay sach honge...','three - love lies betrayal',
              'malegaon me gadbad ghotala','khota sikka - jaat ke thaath','hi fi log','dev d','one by two','oye lucky! lucky oye!',
              'socha na tha','happy bhaag jayegi','manorama six feet under','honeymoon travels pvt. ltd.',
              'ek chalis ki last local','ahista ahista','lottery','roar - tigers of the sundarbans','chakradhaar','players','game',
              'khelein hum jee jaan sey','drona','guru','raavan','delhi 6','bluffmaster','dum maaro dum','bunty aur babli',
              'jhoom barabar jhoom','dostana','all is well','apne ghayal indian','naya pata','a journey of samyak buddha',
              'hum hai raahi car ke','strings - bound by faith','contract','haal - e - dil','dehraadun diary','jashnn','heartless',
              'zed plus','for real','lessons in forgetting','poorna','khanna & iyer','shaapit','bandook','fitoor','daawat e ishq',
              'aashiqui 2','ok jaanu','yeh jo mohabbat hai','dil se poochh... kidhar jaana hai','ek aur murder','feel - the touch',
              '1920 - evil returns','bin bulaye baraati','jaane hoga kya','aao wish karein','darwaza bandh rakho','koi aap sa',
              'aloo chaat','ankahee','red - the dark side','my friend ganesha','umrao jaan','provoked','the mistress of spices',
              'u me aur hum','shivaay','blackmail','cash','atithi tum kab jaoge?','son of sardaar','rascals','main aisa hi hoon',
              'shikhar','insan','zameer - the fire within','toonpur ka superrhero','dil toh baccha hai ji','tango charlie',
              'once upon a time in mumbaai','baadshaho','drishyam','action jackson','apaharan','satyagraha','aakrosh','tezz',
              'halla bol','golmaal - fun unlimited','sunday','golmaal returns','all the best - fun begins','golmaal 3','singham',
              'bol bachchan','singham returns','golmaal again','himmatwala','kaal','omkara','pal pal dil ke saat','jeet lenge jahaan',
              'angry young man','jai balaji mehndipur wale','the world of fashion','lakeer ka fakeer','calendar girls','bloody isshq',
              'faraar','alag','holiday - a soldier is never off duty','the shaukeens','welcome','singh is kinng','thank you','blue',
              'boss','khiladi 786','bewafaa','tees maar khan','entertainment','housefull 3','brothers','jumbo','gabbar is back',
              'once upon a time in mumbaai dobaara!','8 x 10 tasveer','special 26','baby','phir hera pheri','chandni chowk to china',
              'patiala house','rowdy rathore','singh is bling','garam masala','bhagam bhag','bhool bhulaiyaa','de dana dan','khatta meetha',
              'humko deewana kar gaye','family - ties of blood','desi boyz','kambakkht ishq','heyy babyy','housefull','housefull 2','jaan-e-mann',
              'joker','toilet ek prem katha','jolly llb 2','dosti - friends forever','mere jeevan saathi','omg! oh my god','tashan',
              'deewane huye paagal','waqt - the race against time','namastey london','action replayy','pizza','36 china town','naqaab',
              'dahek','aap ki khatir','gandhi my father','short kut - the con is on','mere baap pehle aap','shaadi se pehle',
              'vatsayanana kamasutra - 2','mr. majnu','romeo bola pyar ki aisi ki taisi','sonali cable','khamoshiyan','always kabhi kabhi',
              'baat ban gayi','tere bin laden','london paris new york','chasme baddoor','total siyaapa','dear zindagi','iqraar by chance',
              'runway','pink','bhoothnath returns','cheeni kum','paa','shamitabh','sarkar','nishabd',
              'jai jagdambey maa','ashok chakra tribute to real heroes','dhamkee - the extortion','siddharth - the prisoner',
              'raat gayi baat gayi','i am 24','10ml love','phas gaye re obama','table no. 21','ishq actually','shaitan',
              'samrat & co.','soundtrack','aamir','tera pati mera pyar','radha ne mala japi shyam ki','quick gun murugun',
              'hair is falling','do dilon ke khel mein','riyasat','kaashh....mere hote','wafaa','men will be men',
              'jai mahalaxmi','jism farosh','namkeen','the night of the interview','beehad - the ravine',
              'the unforgettable','blue oranges','kya yahi sach hai','behen hogi teri','boyss toh boyss hain',
              'love sex aur dhokha','citylights','ragini mms','shaadi mein zaroor aana','trapped','be careful',
              'phhir','spark','1920','undertrial','main meri patni aur woh','rama rama kya hai drama',
              'hello hum lallann bol rahe hain','ata pata laapata','hai golmaal in white house','kushti','ladies tailor',
              'masti express','kaisay kahein','ruslaan','ek zakhm - the blast','jai santoshi maa','jaadu sa chal gaya',
              'zanjeer','victoria house','besharam','barfi!','jagga jasoos','bombay velvet','wake up sid','yeh jawaani hai deewani',
              'rockstar','tamasha','ae dil hai mushkil','chillar party','raajneeti','ajab prem ki ghazab kahani','saawariya',
              'rocket singh: salesman of the year','bachna ae haseeno','anjaana anjaani','roy','john day','ru-ba-ru',
              'do lafzon ki kahani','highway','mere khwabon mein jo aaye','karma aur holi','main aur charles','love khichdi',
              'laal rang','murder 3','d','risk','bombay talkies','laaga chunari mein daag','mardaani','aiyyaa','toss',
              'befikre','gunday','band baaja baaraat','ladies vs ricky bahl','goliyon ki raasleela ram - leela','bajirao mastani',
              'kill dil','lootera','dil dhadakne do','mixed doubles','mithya','fatso','kahani ek devi ki...','kshay',
              'maatr','parveen bobby','sweet love','world cupp 2011','raja bhai lagey raho','jeena hai toh thok daal',
              'chitkabrey','ek baar aao na','khwaja mere khwaja','ek baar maza lijiye','super nani','detective naani',
              'do dooni chaar','pyaar mein twist','chintuji','patel ki punjabi shaadi','khushboo','ishq ke parindey',
              'naari teri shakti anokhi','de taali','dhamaal','grand masti','great grand masti','bangistan',
              'tere naal love ho gaya','jaane kahan se aayi hai','malamaal weekly','apna sapna money money','aladin',
              'kal kissne dekha','mahidpur 0 k.m.','life express','calapor','a strange love story','gippi','amdavad junction',
              'mittal vs mittal','hum dum','2 little indians','ugly','udaan','chowrasta - crossroads of love','teree sang',
              'saala khadoos','chand ke paar chalo','mumbai mirror','jackpot','aazaan','jaana pehchana','chhodo kal ki baatein',
              'bose - the forgotten hero','rocky']